---
title: "Tiering Survey"
author: "Federica Rossi"
date: "2023-11-13"
output: 
  html_document:
    code_folding: hide
  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(rmarkdown)
library(readr)
library(readxl)
library("formattable")
library(tidyr)
library(openxlsx)
library(stringr)
library("writexl")

#setwd("/Users/matteo/OneDrive - CNR/bbmri-it-pnrr/survey-wp4-tiering/tiering")
setwd("C:/Users/Antonella/Desktop/bb4FAIR")
quant <- read_excel("./data/quantitativa.xlsx", sheet = "razionale")
quant <- quant[1:14,1:6]
quant <- quant[order(quant$id), ]
survey <- read_excel("./data/231206-risposte.xlsx")
bb <- survey$ID
survey <- as.data.frame(survey[,c(7:44)]) 
bb <- paste0("BB", bb)
```


```{r matrice_punteggi}


punteggi <- matrix(0, nrow = length(bb), ncol = length(quant$id), dimnames = list(bb, quant$domanda))

survey[is.na(survey)] <- "non compilato"

#referente IT 2/H
for (n in c(1:length(survey$`In che ruolo si sta compilando questa survey? `))) {
  
  
  if(survey$`In che ruolo si sta compilando questa survey? `[n] == "Referente informatico"){
    
    punteggi[n,"referente IT"] = quant$completa[1]
    
  }
  
}

#personale dedicato 6/L
for (n in c(1:length(survey$`In caso di risposta positiva, indicare quali delle seguenti attività sono svolte dal personale dedicato della biobanca (risposta multipla)`))) {
 
  if( grepl("Gestione dei dati associati ai campioni", survey$`In caso di risposta positiva, indicare quali delle seguenti attività sono svolte dal personale dedicato della biobanca (risposta multipla)`[n])  ){
    
    punteggi[n,"personale dedicato"] = quant$completa[2]
    
  } else if ((survey$`In caso di risposta positiva, indicare quali delle seguenti attività sono svolte dal personale dedicato della biobanca (risposta multipla)`[n] !="non compilato") && (!("Gestione dei dati associati ai campioni" %in% survey$`In caso di risposta positiva, indicare quali delle seguenti attività sono svolte dal personale dedicato della biobanca (risposta multipla)`[n]))) {
  
  punteggi[n,"personale dedicato"] = quant$parziale[2]
  
}
  
}

#terminologia 9/O
for (n in c(1:length(survey$`Se sì, quali? `))) {
 
  term <- survey$`Se sì, quali? `[n] %>% 
    strsplit(";") %>% 
    unlist()
 
 if ( term[1] != "non compilato" ) {
   
   punteggio = (quant$parziale[3]*length(term))
   
   if (punteggio <= 3) {
     
   punteggi[n,"ontologie"]  = (quant$parziale[3]*length(term))
     
   } else if (punteggio > 3)  {
     
     punteggi[n,"ontologie"] = 3
     
   }
 }
 
}


#cdm P
for (n in c(1:length(survey[,10]))) {
  
  if(survey[n,10] == "Si"){
    
    punteggi[n,"CDM"] = quant$completa[4]
    
  } 
}


#lims T/14
sist_lims <- c("EASYTRACK", "TDBioBank", "LabVantage","REDcap", "Bio Management","NAUTILUS", "MBioLIMS","FREEZERWORKS","TNGB","Olohealth","SmartLab","SmartyBioB","Noraybank")

for (n in c(1:length(survey$`Se esiste un sistema informatico dedicato, di che tipo è (fornire il nome del sistema)? `))) {
 
  lims <- survey$`Se esiste un sistema informatico dedicato, di che tipo è (fornire il nome del sistema)? `[n] %>%
    strsplit( ";|- ") %>% 
    unlist()
  
  lims <- ifelse(grepl("easy", lims, ignore.case = TRUE), "EASYTRACK", lims)
  lims <- ifelse(grepl("bio manag", lims, ignore.case = TRUE), "Bio Management",lims)
  lims <- ifelse(grepl("red", lims, ignore.case = TRUE), "REDcap",lims)
  lims <- ifelse(grepl("td", lims, ignore.case = TRUE), "TDBioBank",lims)
  lims <- ifelse(grepl("home|house", lims, ignore.case = TRUE), "auto sviluppato",lims)
  lims <- ifelse(grepl("wins", lims, ignore.case = TRUE), "WINSAP",lims)
  lims <- ifelse(grepl("FREEZERWORKS", lims, ignore.case = TRUE), "FREEZERWORKS",lims)
  lims <- ifelse(grepl("labvantage", lims, ignore.case = TRUE), "LabVantage",lims)
  lims <- ifelse(grepl("tngb", lims, ignore.case = TRUE), "TNGB",lims)
  lims <- ifelse(grepl("olohealth", lims, ignore.case = TRUE), "Olohealth",lims)
  lims <- ifelse(grepl("NAUTILUS", lims, ignore.case = TRUE), "NAUTILUS",lims)
  lims <- ifelse(grepl("smartlab", lims, ignore.case = TRUE), "SmartLab",lims)
  lims <- ifelse(grepl("MBioLIMS", lims, ignore.case = TRUE), "MBioLIMS",lims)
  lims <- ifelse(grepl("SmartyBioB", lims, ignore.case = TRUE), "SmartyBioB",lims)
  
  for (lim in lims) {
    
    if ( lim %in% sist_lims) {
      
      punteggi[n,"LIMS"] = quant$completa[5]
      break
      
    } else if ( lim == "non compilato") {
  
  punteggi[n,"LIMS"] = quant$vuota[5]
  
    } else {
    
      punteggi[n,"LIMS"] = quant$parziale[5]
  }
    
  }
  
}

#cartella_clinica 15/U
for (n in c(1:length(survey$`Se esiste un sistema informatico dedicato, questo sistema è collegato al sistema di gestione dei dati clinici (per esempio sistemi di cartella clinica o sistemi informativi sanitari territoriali?)`))) {

  cc <- survey[n,15]
  cc <- ifelse(grepl("^si|sì", cc, ignore.case = TRUE), "si",cc)
  cc <- ifelse(grepl("linked", cc, ignore.case = TRUE), "si",cc)
  cc <- ifelse(grepl("biobanca è collegato al", cc, ignore.case = TRUE), "si",cc)
  cc <- ifelse(grepl("previsto", cc, ignore.case = TRUE), "si",cc)
  
  if ( cc == "si" ) {
  
  punteggi[n,"cartella clinica"] = quant$completa[6]
  
  } else {
    
      punteggi[n,"cartella clinica"] = quant$vuota[6]
  }
}


#lims-2 16/V
for (n in c(1:length(survey$`Se NON esiste un sistema informatico dedicato, come sono conservati i dati relativi ai campioni biologici contenuti nella biobanca?`))) {

   if ( survey[n,16] == "non compilato" ) {
  
  punteggi[n,"LIMS-2"] = quant$vuota[7]
  
   }else {
    
      punteggi[n,"LIMS-2"] = quant$completa[7]
  }
}

#infrastruttura IT 17/W
for (n in c(1:length(survey$`L'istituto ha accesso ad una infrastruttura informatica, fisica o virtuale, dedicata ai dati o al processamento dei dati associati ai campioni biologici contenuti nella biobanca?`))) {
  
  if ( survey[n,17] == "Si" ) {
  
  punteggi[n,"Infrastruttura IT"] = quant$completa[8]
  
  } 
}


#storage 19/Y
for (n in c(1:length(survey$`La biobanca ha a disposizione un sistema di storage massivo (capacità maggiori di 20TB), comprendente di backup o sistema di ridondanza (RAID), utilizzabile a scopi di ricerca? `))) {
  
   if ( survey[n,19] == "Si" ) {
  
  punteggi[n,"storage"] = quant$completa[9]
  
  } 
}


#componenti IT 20/Z
for (n in c(1:length(survey$`La biobanca può allocare, autonomamente o tramite il suo CED, risorse di calcolo per dei servizi di Ricerca Federata? (e.g., macchine virtuali, containers, nuovi computer dedicati, etc.). La Ricer...`))) {

  if ( survey[n,20] == "Si" ) {
  
  punteggi[n,"Componenti IT"] = quant$completa[10]
  
  } 
}

#dwh 22/AB
for (n in c(1:length(survey$`L'istituto a cui afferisce la biobanca ha un collettore di dati (quali ad esempio un Data Warehouse o un Data Lake) e/o ha a disposizione una piattaforma di Business Intelligence?"`))) {
 
  if (survey[n,22] == "Si" ) {
  
  punteggi[n,"DWH"] = quant$completa[11]
  
  } 
}

#annotazioni 31/AJ
# for (n in c(1:length(survey[,31]))) {
#  
#   ann <- survey[n,31] %>%
#     strsplit( ";|-") %>% 
#     unlist()
#   ann <- ifelse(grepl("no|non|nessun|na|on|dati", ann, ignore.case = TRUE), "no",ann)
#  
#   if(length(ann)>2){
#     
#     punteggi[n,"annotazioni"] = quant$completa[12]
#     
#   } else if (ann[1] == "no"){ 
# 
#     punteggi[n,"annotazioni"] = quant$vuota[12]
#     
#   } else if ( length(ann)>0 && length(ann)<3) {
#   
#   punteggi[n,"annotazioni"] = quant$parziale[12]
#   
#   }
#   
# }

## annotazioni 30/AI
for (n in c(1:length(survey[,30]))) {
 
  ann <- survey[n,30] %>%
    strsplit( ";") %>% 
    unlist()
  
  punteggio = (quant$parziale[12]*length(ann))
   
   if (punteggio <= 3) {
     
   punteggi[n,"annotazioni"]  = (quant$parziale[12]*length(ann))
     
   } else if (punteggio > 3)  {
     
     punteggi[n,"annotazioni"] = 3
     
   }
  
}


#intersezione dati clinici 34/AN
for (n in c(1:length(survey$`Nel rispetto dei requisiti etici-legali previsti, è possibile incrociare dati relativi ai campioni con dati nei sistemi dell'istituzione o in quelli territoriali?`))) {
 
  if (survey[n,34] == "Si" ) {
  
  punteggi[n,"intersezione dati clinici"] = quant$completa[13]
  
  } else {
    
    punteggi[n,"intersezione dati clinici"] = quant$vuota[13]
    
  }
}

#consenso informato 36/AP
for (n in c(1:length(survey$`Nel rispetto dei requisiti etici-legali previsti, è possibile incrociare dati relativi ai campioni con dati nei sistemi dell'istituzione o in quelli territoriali?`))) {
 
  if (survey[n,36] == "Si" ) {
  
  punteggi[n,"consenso informato"] = quant$completa[14]
  
  } else {
    
    punteggi[n,"consenso informato"] = quant$vuota[14]
    
  }
}

```

```{r tiering}

punteggio_totale <- vector("integer", length = length(punteggi[,1]))

for (n in 1:length(punteggio_totale)) {
  
  punteggio_totale[n] = sum(punteggi[n,])
  
}

punteggi <- punteggi %>%
  cbind(punteggio_totale) %>%
  as.data.frame()

tier_1 <- data.frame(Biobanca = character(), Punteggio = numeric(), stringsAsFactors = F)
tier_2 <- data.frame(Biobanca = character(), Punteggio = numeric(), stringsAsFactors = F)
tier_3 <- data.frame(Biobanca = character(), Punteggio = numeric(), stringsAsFactors = F)

for (score in 1:length(punteggi$punteggio_totale)) {
 
  if (punteggi$punteggio_totale[score]>20) {
    result = c((survey[score,1]), (punteggi[score,15]))
    tier_1 <- rbind(tier_1, result)
      
  } else if (punteggi$punteggio_totale[score]>10){
    result = c((survey[score,1]), (punteggi[score,15]))
    tier_2 <- rbind(tier_2, result)

  } else {
    result = c((survey[score,1]), (punteggi[score,15]))
    tier_3 <- rbind(tier_3, result)
    
  }
  
}

```

```{r stampa_punteggi}

knitr::kable(punteggi, format="markdown", caption = "sommatoria punteggi")
knitr::kable(tier_1[order(as.integer(tier_1[,2]), decreasing = T),], format="markdown", col.names = c("Biobanca", "Punteggio"), row.names = F, caption = "Tier 1")
knitr::kable(tier_2[order(as.integer(tier_2[,2]), decreasing = T),], format="markdown", col.names = c("Biobanca", "Punteggio"),  row.names = F, caption =  "Tier 2")
knitr::kable(tier_3[order(as.integer(tier_3[,2]), decreasing = T),], format="markdown", col.names = c("Biobanca", "Punteggio"),  row.names = F, caption = "Tier 3")

```

```{r file_excel}

row <- gsub("\\.", " ", rownames(punteggi))
punteggi$`Nome biobanca` <- row
punteggi <- punteggi %>%
  relocate(`Nome biobanca`)

# wb <- createWorkbook()
# addWorksheet(wb, sheetName = "punteggi_totali")
# addWorksheet(wb, sheetName = "tier_1")
# addWorksheet(wb, sheetName = "tier_2")
# addWorksheet(wb, sheetName = "tier_3")
# 
# writeData(wb, sheet = "punteggi_totali", punteggi)
# writeData(wb, sheet = "tier_1", tier_1, colNames = F)
# writeData(wb, sheet = "tier_2", tier_2, colNames = F)
# writeData(wb, sheet = "tier_3", tier_3, colNames = F)
# 
# saveWorkbook(wb, "punteggi_tiering.xlsx")

```

```{r terzili}

punteggi <- punteggi[order(punteggi$punteggio_totale, decreasing = T),]

terzile_1 <- data.frame(Biobanca = character(), Punteggio = numeric(), stringsAsFactors = F)
terzile_2 <- data.frame(Biobanca = character(), Punteggio = numeric(), stringsAsFactors = F)
terzile_3 <- data.frame(Biobanca = character(), Punteggio = numeric(), stringsAsFactors = F)

max_ter = round((length(punteggi$punteggio_totale)/3))

for (num in 1:length(punteggi$punteggio_totale)) { 
  
  if (num <= max_ter) {
    
    biobanca <- data.frame( Biobanca =row[num], Punteggio = punteggi[num,"punteggio_totale"])
    terzile_1 <- rbind(terzile_1, biobanca)
    
  } else if (num <= max_ter*2) {
    
    biobanca <- data.frame( Biobanca = row[num], Punteggio = punteggi[num,"punteggio_totale"])
    terzile_2 <- rbind(terzile_2, biobanca)
    
  } else if (num <= max_ter*3) {
    
    biobanca <- data.frame( Biobanca = row[num], Punteggio = punteggi[num,"punteggio_totale"])
    terzile_3 <- rbind(terzile_3, biobanca)
    
  }

}

```

```{r stampa_terzili}

knitr::kable(terzile_1[order(as.integer(terzile_1[,2]), decreasing = T),], format="markdown", col.names = c("Biobanca", "Punteggio"), row.names = F, caption = "Terzile 1")
knitr::kable(terzile_2[order(as.integer(terzile_2[,2]), decreasing = T),], format="markdown", col.names = c("Biobanca", "Punteggio"),  row.names = F, caption =  "Terzile 2")
knitr::kable(terzile_3[order(as.integer(terzile_3[,2]), decreasing = T),], format="markdown", col.names = c("Biobanca", "Punteggio"),  row.names = F, caption = "Terzile 3")

```




